name: 'Release helm chart'
description: 'Releases helm charts using semantic-release with the @unsupervised/release-config-helm release config. This action uses main and alpha branches and releases. This action deletes the alpha branch and re-creates it from main after a release from main'
inputs:
  token:
    description: github token to use for the release, if you want this to trigger other workflows such as flows on release created, pass in a PAT
    required: false
    default: ${{ github.token }}
  tag:
    description: 'Release tag to fetch chart from'
    required: false
    default: ${{ github.event.release.tag_name }}
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
  sentry-auth-token:
    description: 'Sentry auth token to facilitate sentry releases'
    required: false
    default: false
  sentry-org-slug:
    description: 'Sentry org name to facilitate sentry releases'
    required: false
    default: false
  sentry-project-name:
    description: 'Sentry project to update with release info'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
        branch: alpha
    - id: semantic-release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extends: '@unsupervised/release-config-helm'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - uses: dawidd6/action-git-user-config@v1
      if: github.ref == 'main' && always()
    - name: merge main to alpha
      if: github.ref == 'main' && always()
      shell: bash
      run: |
        git pull
        git checkout alpha
        git merge --no-ff --strategy-option theirs -m "merge main to alpha after release" main
        git push --set-upstream origin alpha
    - if: ${{ (inputs.sentry-auth-token != 'false') }}
      name: sentry release
      uses: getsentry/action-release@v1.1.6
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org-slug }}
        SENTRY_PROJECT: ${{ inputs.sentry-project-name }}
      with:
        version: ${{ inputs.tag }}
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on on alpha
      with:
        token: ${{ inputs.token }}
        include-admins: true
        branch: alpha
